# Generated by Django 4.2.6 on 2023-12-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_asset', models.CharField(max_length=233)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
