# Generated by Django 4.2.6 on 2023-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut', '0003_alter_asset_name_of_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name_of_asset',
            field=models.CharField(max_length=255),
        ),
    ]
