# Generated by Django 4.2.6 on 2023-12-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut', '0005_asset_timestamp_alter_asset_name_of_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name_of_person',
            field=models.CharField(default='Joe', max_length=20),
        ),
    ]
