# Generated by Django 4.2.6 on 2023-12-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut', '0007_remove_asset_name_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name_of_person',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
